/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class OptimizelyTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, OptimizelyTimeoutError.prototype);
    }
}
