/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChatCompletionsUsageDto {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
}
