/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Optimizely from "..";

export interface ChatRequestDto {
    model: string;
    messages: Optimizely.ChatMessageDto[];
}
