/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Optimizely from "..";

export interface ChatCompletionsResponseDto {
    completion: Optimizely.ChatMessageDto;
    usage: Optimizely.ChatCompletionsUsageDto;
}
