/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ModelDto {
    name: string;
    vendorName: string;
    vendor: string;
    tokenLimit: number;
    millicentsPer1K: number;
}
