/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Optimizely from "..";

export interface ValidationError {
    loc: Optimizely.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
