/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Optimizely from "../../api";
import * as core from "../../core";

export const ChatCompletionsResponseDto: core.serialization.ObjectSchema<
    serializers.ChatCompletionsResponseDto.Raw,
    Optimizely.ChatCompletionsResponseDto
> = core.serialization.object({
    completion: core.serialization.lazyObject(async () => (await import("..")).ChatMessageDto),
    usage: core.serialization.lazyObject(async () => (await import("..")).ChatCompletionsUsageDto),
});

export declare namespace ChatCompletionsResponseDto {
    interface Raw {
        completion: serializers.ChatMessageDto.Raw;
        usage: serializers.ChatCompletionsUsageDto.Raw;
    }
}
