/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Optimizely from "../../api";
import * as core from "../../core";

export const ChatMessageDto: core.serialization.ObjectSchema<
    serializers.ChatMessageDto.Raw,
    Optimizely.ChatMessageDto
> = core.serialization.object({
    role: core.serialization.string(),
    content: core.serialization.string(),
});

export declare namespace ChatMessageDto {
    interface Raw {
        role: string;
        content: string;
    }
}
