/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Optimizely from "../../api";
import * as core from "../../core";

export const ModelsResponseDto: core.serialization.ObjectSchema<
    serializers.ModelsResponseDto.Raw,
    Optimizely.ModelsResponseDto
> = core.serialization.object({
    models: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ModelDto)),
});

export declare namespace ModelsResponseDto {
    interface Raw {
        models: serializers.ModelDto.Raw[];
    }
}
