/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Optimizely from "../../api";
import * as core from "../../core";

export const TokensResponseDto: core.serialization.ObjectSchema<
    serializers.TokensResponseDto.Raw,
    Optimizely.TokensResponseDto
> = core.serialization.object({
    tokens: core.serialization.number(),
});

export declare namespace TokensResponseDto {
    interface Raw {
        tokens: number;
    }
}
